name: bread title
dough_serving: 500.0  # recommended dough size
batch_size: 2         # recommended batch size
components:
  -
    name: poolish
    ingredients:
      - [all purpose flour,  75.0,  true]
      - [whole wheat flour,  75.0,  true]
      - [water,             150.0, false]
      - [yeast,               1.0, false]
  -
    name: mix # a formula must have a segment called mix
    ingredients:
      - [all purpose flour, 450.0,  true]
      - [whole wheat flour, 150.0,  true]
      - [water,             500.0, false]
      - [poolish,           300.0, false]
